### ISSUE TITLE
Layered interface layers

### ISSUE THREAD

**Issue by galgalesh** [juju-solutions/charms.reactive#102]
We need a way to share code between interface layers.

# `rest-api` extends `http`

Consider a database WololoDB® with an HTTP REST API. The charm for WololoDB should implement the generic `http` interface to connect to reverseproxies, loadbalancers, https endpoints etc. The charm should also implement a specific `wololodb` interface for clients who want to talk to the database. So we have two interface layers:

- `http` sends the hostname and the port and tells Juju that it can connect to other charms implementing the `http` interface.
- `wololodb` sends the hostname and port and tells Juju that it can connect to other charms implementing the `wololodb` interface.

Although both interfaces are identical, they need to be separate so that Juju knows that a `wololodb` client can only connect to a WololoDB server, not all HTTP servers.

This maps very cleanly to layers, the `wololodb` interface uses the `http` interface as base interface layer.

Whatever we come up with for reactive 2.0 should enable this kind of layered approach to interfaces.

# Totally epic

Juju should understand the interface inheritance. The HAProxy charm is a great use-case for this. The `reverseproxy` relationship has two "modes", the default mode compatible with the normal `http` interface, and an advanced mode where more info is shared over the relationship.

This would result in two interfaces

 - `http`
 - `reverseproxy` which `includes: ['http']`

When an operator connects a charm to haproxy, Juju knows that the `reverseproxy` relationship is preferred over the `http` relationship if both charms implement that interface.

**Comment by ajkavanagh** [comment]
This is a bit of a tangent, but related to this discussion:

## Specialness of interfaces

I had thought one of the objectives of charms.reactive 2 was to remove the "special-ness" of interfaces and just consume them as layers.  I'm guessing the current setup with an interface is so that it generates the hooks in the `/hooks` directory, but I'm not sure what the plan was to be able to still generate the appropriate hooks without explicit configuration to indicate that a layer actually contains interface code?  So perhaps I got that bit wrong.  Maybe the explicit 'interface' configuration is still needed to generate the hooks.  Thoughts?

## Code reuse

Python already has an excellent code sharing facility: python modules.

My understanding of the purpose of **building** a charm is to ensure that all of the software necessary to run the charm (i.e. invoke a hook) is present in the built charm so that no further installation (for the charm itself) is necessary.  This is achieved using the `wheelhouse.txt` to grab the python modules needed (and that can also be from git/bzr/other) and compile them into wheel which is built alongside the charm.

For the OpenStack charms, we need to be able to share large amounts of code between charms.  Thus, rather than using layers as a **code** re-use mechanism, we use layers to specify particular interfaces that are needed for different types of charm (API, HA) and then have a shared module (`charms.openstack`) that we use to share code between charms.  This gets pulled into the charm using the `wheelhouse.txt` in the base `layer:openstack-api`.  e.g. the `layer.yaml` from `layer:openstack-api` is:

```yaml
includes: ['layer:openstack-principle', 'interface:mysql-shared',
           'interface:rabbitmq', 'interface:keystone',
           'interface:hacluster', 'interface:openstack-ha']
repo: 'https://github.com/openstack/charm-layer-openstack-api'
```

However, I suspect that this discussion is about how interface code is shared directly between interfaces.

## Thoughts on this proposal

At present, layers and interfaces seem to only communicate via flags (states in old-speak).  Interfaces are a bit special in that you can obtain the interface instance and use methods on that to communicate.  If this was generalised such that a layer could associate an instance with a flag, then richer behaviours could be implemented between layers; however, I've not thought through (and therefore, don't know) the usefulness of that type of approach.

Obviously, this doesn't share code, rather it's just accessing code across layers and interfaces.  So how to share code?

I'm guessing that this is something to do with inheriting from the `RelationBase` classes in the `requires.py` and `provides.py` files in the interface (charms.reactive 1) or the upcoming (suggested) `Flag()` class in the same files for charms.reactive 2.

This might be a bit brittle, but no more than relying on other python modules.  The code for http would be in `relations.http.provides` and `relations.http.requires`.

Obviously, from a unit testing perspective, this is something else that would have to be mocked, but from a functional test, is no different as the charm still needs to be built for the functional tests to run.

## Summary

I can see why there is a requirement for inheriting interfaces, but not an obvious solution that isn't brittle.

Also, the final part around juju doing the determination on the interface would mean a change to Juju rather than reactive.  I would probably argue for explicitness rather than implicit behaviour to stop *surprises* from happening.
