### ISSUE TITLE
0.5.0.b0: charms.reactive.bus.get_state is missing (charms.openstack)

### ISSUE THREAD

**Issue by ajkavanagh** [juju-solutions/charms.reactive#124]
As part of the testing of of the 0.5.0.b0 tagged release, barbican (which is built with `charms.openstack`) has the following error:

```
2017-09-18 14:32:01 DEBUG install     if not self.get_state('haproxy.stat.password'):
2017-09-18 14:32:01 DEBUG install   File "/usr/local/lib/python3.5/dist-packages/charms_openstack/charm/core.py", line 348, in get_state
2017-09-18 14:32:01 DEBUG install     return reactive.bus.get_state(state)
2017-09-18 14:32:01 DEBUG install AttributeError: module 'charms.reactive.bus' has no attribute 'get_state'
```

In `charms.openstack` the get_state, set_state and remove_state are used as:

```python
    def set_state(self, state, value=None):
        """proxy for charms.reactive.bus.set_state()"""
        reactive.bus.set_state(state, value)

    def remove_state(self, state):
        """proxy for charms.reactive.bus.remove_state()"""
        reactive.bus.remove_state(state)

    def get_state(self, state):
        """proxy for charms.reactive.bus.get_state()"""
        return reactive.bus.get_state(state)
```

These tend to be used quite heavily in `charms.openstack` derived charms.  One way to fix it (on the `charms.openstack` side) would be to just:

```python
    def set_state(self, state, value=None):
        """proxy for charms.reactive.bus.set_state()"""
        try:
            reactive.bus.set_state(state, value)
        except AttributeError:
            ...set_flag(state, value)
```

... and also adding `set_flag(...)` *et al.* to `charms.openstack` and adding deprecations to the `set_state(...)` *et al.* functions.

Not sure on the best approach here.

**Comment by johnsca** [comment]
Part of #112 was to move all flag-related code into [`charms.reactive.flags`](https://github.com/juju-solutions/charms.reactive/blob/master/charms/reactive/flags.py).  They are also available at the top level of [`charms.reactive`](https://github.com/juju-solutions/charms.reactive/blob/master/charms/reactive/__init__.py).  I can create shims in `charms.reactive.bus` but it's a little tricky because there is already an import dependency from flags on bus, which would create an import loop.  If you're already using wrappers, would it be easy to change that one spot from `reactive.bus.X` to `reactive.flags.X`?  Otherwise, I can do a lazy import to handle the loop and provide a transition path since the PR broke backwards compatibility because I assumed everyone was using the top-level import (from `__init__`).

Additionally, `get_state` was only ever intended as an internal implementation detail, and one that I'd like to get rid of as we transition to the new style relations (`Endpoint`).  I highly recommend that you instead use [`is_flag_set`](https://github.com/juju-solutions/charms.reactive/blob/master/charms/reactive/flags.py#L131) instead.  But, again, if we need a transitional shim, we can make that work.

**Comment by ajkavanagh** [comment]
It's probably a good idea to move `charms.openstack` to only use the "official" public interface of `charms.reactive`.  So, I've raised this [bug](https://bugs.launchpad.net/charms.openstack/+bug/1718208) to capture it in charms.openstack.
