### ISSUE TITLE
Ignore 'update-status' by default

### ISSUE THREAD

**Issue by hloeung** [juju-solutions/charms.reactive#139]
Hi,

The update-status hook by default fires every 5 minutes. A lot of reactive charms are written to write out configs and restart the daemons that uses them. Unfortunately, update-status triggers these and causes issues where daemon services are offline during restart. An example of this is NRPE.

While we can work around this, it's quite hacky. Either check hook name and then return on update-status on the various handlers or some other hack such as the examples @stub42 has provided for **every single reactive charm**:

`from functools import wraps

def when_not_update_status(f):
    @wraps(f)
    def wrapper(*args, **kw):
        if hookenv.hook_name() == 'update-status':
            return
        return f(*args, **kw)
    return wrapper`

`from functools import wraps

def when_not_hook(*hooks):
    def decorator(f):
        @wraps(f)
        def wrapper(*args, **kw):
            for hook in hooks:
                if hookenv.hook_name() == hook:
                    return
            return f(*args, **kw)
        return wrapper
    return decorator`

I think we should change it and unwire update-status so it doesn't trigger handlers in the main reactive loop. Instead, have a configuration switch or something charm authors who specifically want to do stuff in update-status to do so.

**Comment by galgalesh** [comment]
One of the issues is that some charms now rely on this behavior.. I personally think the update-status hook should've never been created, 5 minutes is so arbitrary, and polling for new status doesn't scale well, but there's not much the reactive framework can do at this point.

We've talked about this internally and our consensus is that the reactive framework actually shouldn't do anything when nothing has changed. Handlers should only be reinvoked if the flags they react to have changed. Re-invoking every handler whose flags match in every hook isn't a good idea.. So that's our long-ish-term plan: handlers will only get reinvoked when something has actually changed. What do you think of this?

Short-term plan is that you should simulate this behavior with flags. It is currently already possible to only run code when something has actually changed. I'm happy to take a look at your code and figure out how we can fix this with the current implementation. Are you free to share the code in question?

**Comment by paulgear** [comment]
I actually find it hard to believe that many charms depend on this behaviour.  At least, in my experience the number of charms affected by bad repeated application of hooks in update-status outweighs the number of charms relying on update-status to actually make changes by a large margin.

Update status is an important hook; sensible use of it makes charms a lot easier to work with (i.e. using it to actually update the status message to provide visibility into your charm's decisions).  But it's not like the other hooks, doesn't need to be, and I think we could find and eliminate the cases which rely on it making changes reasonably quickly.

My suggestion is to add a flag to reactive to say "treat update-status like all the other hooks".  It should default to true.  When set to false, it would only run things flagged @hook('update-status').  We could publicise the default value as deprecated (and warn when someone uses charm proof and/or charm build), and at some later date, change the default to false.

Alternatively, we could provide another mechanism, like an update-status.d directory whose contents are run instead of the usual hooks.  If charms want to use them for making changes, they can, and if they only want to make status changes, they don't need to do anything relating to reactive states.

**Comment by jacekn** [comment]
> the reactive framework actually shouldn't do anything when nothing has changed. Handlers should only be reinvoked if the flags they react to have changed.

I think change like this could cause problems to some charms. It's IMO a reasonable idea to ensure things are the way they are supposed to be even if states don't change. Example dummy code:

    @when("service.started")
    def ensure_started():
        # Check if service alive, start if needed
        # Publish workload status message warning user

If you stop firing "ensure_started" handler then part of the functionality will be lost. Maybe we could do a quick charm audit to find out how many of them rely on this behavior before making the change?

@hloeung use code blocks like this in my charms:

    @when_not("software.installed")
    def install_software():
        # Do whatever needs to be done
        set_state("software.installed")

Above is IMO easy to understand and I can `remove_state("software.installed")` anywhere to trigger handler regardless of hook I'm in.
