### ISSUE TITLE
Documentation missing for execd support

### ISSUE THREAD

**Issue by jacekn** [juju-solutions/charms.reactive#142]
I've just spent some time implementing exec.d support in my layer. I was close but then I was told that this is supported by the base layer out of the box:

https://github.com/juju-solutions/layer-basic/blob/master/lib/charms/layer/execd.py

I searched documentation here:

https://charmsreactive.readthedocs.io

But there is nothing about it.

Could this very useful feature be documented in an easily searchable and discoverable place?

**Comment by galgalesh** [comment]
That is a useful feature, I didn't know about that! I'll add it to the docs.

Since I didn't even know this existed, I'm not the best person to write docs on this. Do you mind lending a hand?

- Do you have any examples of charms using this?
- Can you share some details about your use-case?
- Is `execd` a canonical name for such a feature or are there some other keywords we should include for when people search for this? Names of similar features in other mgmt tools?

**Is the following text sufficient, or do we need to add more info to this?**


```
execd/preinstall
It is often necessary to configure and reconfigure machines
after provisioning, but before attempting to run the charm.
Common examples are specialized network configuration, enabling
of custom hardware, non-standard disk partitioning and filesystems,
adding secrets and keys required for using a secured network.
The reactive framework's base layer invokes this mechanism as
early as possible, before any network access is made or dependencies
unpacked or non-standard modules imported (including the charms.reactive
framework itself).
Operators needing to use this functionality may branch a charm and
create an exec.d directory in it. The exec.d directory in turn contains
one or more subdirectories, each of which contains an executable called
charm-pre-install and any other required resources. The charm-pre-install
executables are run, and if successful, state saved so they will not be
run again.
    $JUJU_CHARM_DIR/exec.d/mynamespace/charm-pre-install
An alternative to branching a charm is to compose a new charm that contains
the exec.d directory, using the original charm as a layer,
A charm author could also abuse this mechanism to modify the charm
environment in unusual ways, but for most purposes it is saner to use
charmhelpers.core.hookenv.atstart().
```



*PS: The documentation now lives on readthedocs. We're locked out of the pythonhosted docs because they're being depricated. It's a complete shitfuck, but there's not much we can do.. I changed the URL in your question in order to try to convince Google not to send people there. We'll delete the docs on pythonhosted soon.*

**Comment by stub42** [comment]
I approve the text taken from the docstring because I wrote it :)
