### ISSUE TITLE
Discovery importing dependent modules multiple times

### ISSUE THREAD

**Issue by stub42** [juju-solutions/charms.reactive#33]
If I have reactive/a.py and reactive/b.py that both import lib/shared.py, shared.py ends up being imported twice times and any side effects run twice. Global state will be reset, potentially discarding modifications made by a.py or b.py. atstart/atexit handlers will be registered multiple times.

Work around is to import the modules from the hooks/ stub.

**Comment by johnsca** [comment]
Re-imports are supposed to handled automatically.  I'm guessing this is related to #31 and we need switch to use `import_module` instead of `load_module`; I used the former due to not needing to change PYTHONPATH / sys.path, but I think that it is much less robust and we should just do the path adjustments.

**Comment by stub42** [comment]
I believe the multiple imports are happening because:

```python
modname = realpath.replace('.', '_').replace(os.sep, '_')
sys.modules[modname] = load_source(modname, realpath)
return sys.modules[modname]
```

Here, realpath is the full path to the file, so the module gets imported into sys.modules['var_lib_juju_[...]_reactive_foo.py'] instead of just the module name.
