### ISSUE TITLE
First hook vs install hook

### ISSUE THREAD

**Issue by stub42** [juju-solutions/charms.reactive#52]
With Juju storage coming out of experimental, the first hook run on a unit may no longer be the install hook. If initialization such as package installation is left until the install hook, handlers will fail if they are invoked earlier from a storage hook.

One option is to deprecate ```@hook('install')``` in favor of some other decorator doing the moral equivalent of ```@hook('install', '*-storage-attached')```. It wouldn't matter if this is invoked exactly once or potentially multiple times provided the behaviour is documented. Note that a layer does not know the names of the storage declared by the charm using it, and has no syntax available to declare this hook itself.

Another option is I could make a layer, exposing some state allowing handlers to guard from being run too early (or people simply set their own state of course). I suspect this is more error prone in practice.

**Comment by johnsca** [comment]
The pattern that I've adopted, and that I've seen several other charm authors use, is to eschew `@hook('install')` in favor of `@when_not('my_charm.installed')`.  I think that makes it clear what the real condition is (something is not installed that needs to be, regardless of what life-cycle event we're responding to), and avoids the issue you mentioned.

In general, I think `@hook` should be avoided at all costs.  The only place I use it is in interface layer classes, and because of that those suffer from issues with upgrades and debugging.  I'm really thinking that the framework needs to provide a synthetic state for connected relations so that we can deprecate `@hook` entirely.

**Comment by stub42** [comment]
Yup. I do keep wrestling with needing certain handlers to be run before others, which is fine for a single layer but difficult when dealing with multiple layers. For example, my charm needs to ensure a particular operation happens before the apt layer handlers kick in and install the extra_packages declared by the operator. I need the ```@hook``` decorator for this, and will need a few once I add Juju storage support, but this is a perfectly workable solution for my needs.
