### ISSUE TITLE
Handling departed hooks in interface layers: relation information is not available.

### ISSUE THREAD

**Issue by tasdomas** [juju-solutions/charms.reactive#69]
It is difficult to handle departed relations in interface layers because the relation data is not available.
```conversation.get_remote(key)``` return nothing even though the relation value is available using the relation-get hook tool.

**Comment by chuckbutler** [comment]
I ran into this last-night. I can confirm this is an issue, even in the -departed hook.

I'm not certain if this is a byproduct of the unit racing to termination, or if this is a bug in reactive. I'm leaning towards a reactive bug, due to the nature of still being able to access the relation value, during the -departed hook from the hookenv tooling.

**Comment by johnsca** [comment]
This is happening because `relation-list` no longer includes the departing remote unit, even though you can still access the data.  There is a fix in the referenced PR that makes it use the internal list of units and not depend on Juju to tell us what it is.
