### ISSUE TITLE
'conversation.set_state' is too ambiguous, should use 'conversation.add_to_state'

### ISSUE THREAD

**Issue by sebastienpattyn93** [juju-solutions/charms.reactive#88]
After debugging for 2.5 hours together with @galgalesh, I finally found that our code was completely wrong due to our understanding of the following function.

    conversation.set_state('{relation_name}.state')

Our understanding was that this adds that state to the conversation, while in fact it is actually the other way around; This function adds the conversation to that state.

Suddenly everything makes sense:

- Relationship states contain conversations because you create them by adding a conversation to a state.
- Normal states don't contain relationships because you create them by creating the state.
- Removing a relationship from a state 
- A relationship state without conversations gets removed.
- An "x.broken" state contains all the conversations that were "broken".
- etc...

To prevent other people from tripping over this, it might be best to alias `conversation.set_state` to `conversation.add_to_state('{relation_name}.state')`. That would make it more clear what this function does exactly. Similarly, alias `conversation.remove_state` to `conversation.remove_from_state`. You are not adding or removing a state to/from a conversation, you are adding and removing a conversation to/from a state.

**Comment by galgalesh** [comment]
The whole conversations framework makes so much sense now!

- When using `GLOBAL` all units share the same conversation. The "conversation state" will only have one conversation because `conv.add_state` adds the same conversation to the state every time
- When using `GLOBAL`, all units share the conversation so `self.conversations()` will only show one conversation.

So if I'm correct, the object you get if you react to a "relation state" is that state itself? So the classes you create in `provides.py` and `requires.py` are actually those state objects?

If this is correct, wouldn't it then make sense to alias `RelationBase` into `RelationStateBase`? Does this mean that it is possible to create my own "State Classes" similar to RelationBase?

**Comment by johnsca** [comment]
I agree that `add_state` or `add_to_state` are better.  However, the relation instances are not quite the same thing as state objects.  There isn't really a state object, as it's just a flag with some optional associated data (the relation instances).  However, I think that making an explicit state object is an interesting idea that could make the relationship between states and units more clear, allowing us to do away with the conversation model, as well as making the call signatures more consistent.
