### ISSUE TITLE
Reaction on config set doesn't work as implied by docs

### ISSUE THREAD

**Issue by dannf** [juju-solutions/charms.reactive#89]
I'm trying to write reactive code that will run when a config gets set. The docs[1] include an example where there's a config called 'admin-pass' and the reactive code uses the config key directly:

"...the following would update a config file when both a database and admin password were available..."
@when('db.database.available', 'admin-pass')

However, I couldn't get this to work. That is, if I have 'foo' defined in config.yaml, and use the following code:

    @when('foo')
    def foo():
        log("foo is set")

I don't see "foo is set" get logged after I run 'juju config service foo=5'.

[1] https://charmsreactive.readthedocs.io

**Comment by stub42** [comment]
That example predates the config states set by the base layer. It is technically correct, although it omits the handler that sets the 'admin-pass' state. I agree that it would be clearer if we changed `@when('db.database.available', 'admin-pass')` to `@when('db.database.available', 'config.set.admin-pass')`. Its still not a brilliant example though, since the handler rewrites the config unnecessarily and really needs a data_changed guard to stop it doing that when the password or database credentials are unchanged.

**Comment by galgalesh** [comment]
Fixed by latest docs
