### ISSUE TITLE
Config validation

### ISSUE THREAD

**Issue by stub42** [juju-solutions/charms.reactive#98]
Charms need to be able to validate their configuration, going into a blocked state until the operator fixes invalid configuration.

charms.reactive should make this easy.

The PostgreSQL charm does this using an `@preflight` mechanism. The hook validates the configuration, and if it fails, sets the blocked state and does sys.exit(0). I do not think this is a good approach, because of the sys.exit(0) hack to abort the process.

You can't do this with standard reactive handlers, because during a config-changed hook handlers may attempt to run using invalid configuration before the config validation handler has had a chance to run.

I do not have an elegant solution to propose.

**Comment by galgalesh** [comment]
# In general

I think it's good to create a list of issues of stuff that we want to do but can't currently do with the reactive framework. Ideally, we'll find a single solution that allows us to do all these things **with** the reactive framework instead of **in** the reactive framework.

It's preferable to keep the reactive framework as lean as possible and to enable charm developers to put such functionality in a layer.

# Why can't this be done currently?

One way to do this is to have a `config.checked` flag. Each handler that uses the config has the `@when('config.checked)` condition. You create a handler that sets the `config.checked` flag after it checked the config.

The issue with this approach is that the `config.checked` flag will still be enabled when the config changes in a subsequent run.

# How can we solve this?

As a strawman, I'll use the idea of linked states from issue https://github.com/juju-solutions/charms.reactive/issues/97

```python
# Every time `config.changed` gets set, `config.checked` gets removed immediately; before
# running the next handler
reactive.if_this_then_remove('config.changed', 'config.checked')

@when("config.changed")
@when_not("config.checked")
def  check_config():
    if is_valid_config() :
         set_flag('config.checked')

@when(
    "config.checked",
    "config.changed.port",
)
def set_port():
    # ...
```

Clean solution that enables developers to create their own check logic. This has a few advantages:

 - Charmers can make their checking logic as complex as they want
 - Charmers can put checking logic in a layer, for example a layer that checks if certain config options are valid json. You specify which config options should be checked using layer options.
- Charmers can build on top of existing "checking" layers to implement more thorough checking logic. Example: One layer checks if config value is valid json; another layer checks if the json objects have the schema that you want.

And most importantly: **We can be lazy without being a blocker for charm development.**

**Comment by ajkavanagh** [comment]
I'm still slightly allergic to putting code that runs on module import, so a possible modification to @galgalesh code is:

```python
@when("config.changed", "config.checked")
def remove_config_checked():
    remove_flag('config.checked')

@when("config.changed")
@when_not("config.checked")
def  check_config():
    if is_valid_config() :
         set_flag('config.checked')

@when(
    "config.checked",
    "config.changed.port",
)
def set_port():
    # ...
```

However, there's **still** a problem with code in a _layer_ needing to run before any other code.  e.g. the situation where we want a package installed before code in a higher layer can run.

I wonder if some sort of specification for declaring the flags a layer is both dependent on _and_ provides for other layers to use. (So, this would make it explicit that the layer communicates some idea of 'state' to other layers).  Thus, the README for a layer would specifically indicate what preconditions _it_ expects with respect to other layers (i.e. all of it's handlers gate until a flag is true) and what postconditions it provides (e.g. a set of flags to indicate when it is ready).  Implementation detail might just be to gate internally.

This is already kind of implemented in interfaces which use '{relation-name}.connected' and '{relation-name'.available' as a (sort of) convention to indicate whether they can be consumed.

i.e. I'm advocating an explicit convention, and perhaps providing some framework support for detecting/supporting 'layer-level flags'.

TBD?

**Comment by galgalesh** [comment]
This is now possible using triggers.
